import { useState } from 'react';
import { toast } from '../../store/toast-store';
import { Button, Input } from '../common';
import type { Project, TestResult } from '../../models/types';
import './EmailDialog.css';

interface EmailDialogProps {
  project: Project;
  results: TestResult[];
  onClose: () => void;
}

export function EmailDialog({ project, results, onClose }: EmailDialogProps) {
  const [recipient, setRecipient] = useState('');
  const [subject, setSubject] = useState(`Accessibility Report: ${project.name}`);
  const [additionalMessage, setAdditionalMessage] = useState('');

  // Calculate stats
  const total = results.length;
  const passed = results.filter((r) => r.conformance === 'Supports').length;
  const failed = results.filter((r) => r.conformance === 'Does Not Support').length;
  const partial = results.filter((r) => r.conformance === 'Partially Supports').length;
  const na = results.filter((r) => r.conformance === 'Not Applicable').length;
  const notTested = results.filter(
    (r) => (r.conformance as string) === 'Not Tested' || !r.conformance
  ).length;

  const generateBody = () => {
    return `Hello,

Here is the accessibility conformance report for ${project.name}.

Project Details:
- Name: ${project.name}
- URL: ${project.description || 'N/A'}
- Target Level: WCAG ${project.targetConformanceLevel}
- Date: ${new Date().toLocaleDateString()}

Audit Summary:
- Total Criteria: ${total}
- ✅ Supports: ${passed}
- ⚠️ Partially Supports: ${partial}
- ❌ Does Not Support: ${failed}
- ➖ Not Applicable: ${na}
- ⚪ Not Tested: ${notTested}

${additionalMessage ? `\nNote:\n${additionalMessage}\n` : ''}
Please find the detailed report attached (PDF/JSON).

Generated by VPAT Creator`;
  };

  const handleOpenEmail = () => {
    const body = generateBody();
    const mailtoLink = `mailto:${recipient}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(mailtoLink, '_blank');
    onClose();
  };

  const handleCopyBody = () => {
    navigator.clipboard.writeText(generateBody());
    toast.success('Email body copied to clipboard!');
  };

  return (
    <div className="email-dialog">
      <div
        className="email-dialog__overlay"
        onClick={onClose}
        role="button"
        tabIndex={0}
        onKeyDown={(e) => e.key === 'Escape' && onClose()}
        aria-label="Close dialog"
      />

      <div className="email-dialog__content" role="dialog" aria-modal="true">
        <div className="email-dialog__header">
          <h2>📧 Email Report</h2>
          <button className="email-dialog__close" onClick={onClose} aria-label="Close">
            ×
          </button>
        </div>

        <div className="email-dialog__body">
          <div className="email-dialog__note">
            <span>⚠️</span>
            <p>
              This will open your default email client with a drafted message.
              <strong> You must manually attach the exported PDF or JSON file</strong> to the email
              before sending.
            </p>
          </div>

          <Input
            label="To (Email Address)"
            value={recipient}
            onChange={(e) => setRecipient(e.target.value)}
            placeholder="client@example.com"
            type="email"
            fullWidth
          />

          <Input
            label="Subject"
            value={subject}
            onChange={(e) => setSubject(e.target.value)}
            fullWidth
          />

          <div className="email-dialog__field">
            <label
              htmlFor="additional-message"
              style={{
                display: 'block',
                marginBottom: '0.5rem',
                fontSize: '0.875rem',
                fontWeight: 500,
                color: '#64748b',
              }}
            >
              Additional Message
            </label>
            <textarea
              id="additional-message"
              className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-500"
              rows={3}
              value={additionalMessage}
              onChange={(e) => setAdditionalMessage(e.target.value)}
              placeholder="Add any specific notes or context here..."
              style={{ width: '100%', resize: 'vertical', minHeight: '80px' }}
            />
          </div>

          <div className="email-dialog__preview">
            <span style={{ display: 'block', marginBottom: '0.5rem', fontWeight: 500 }}>
              Message Preview
            </span>
            <div className="email-dialog__preview-content">{generateBody()}</div>
            <div style={{ marginTop: '0.5rem', textAlign: 'right' }}>
              <Button variant="secondary" size="sm" onClick={handleCopyBody}>
                📋 Copy Text
              </Button>
            </div>
          </div>
        </div>

        <div className="email-dialog__footer">
          <Button variant="secondary" onClick={onClose}>
            Cancel
          </Button>
          <Button variant="primary" onClick={handleOpenEmail}>
            Open Email Client ↗
          </Button>
        </div>
      </div>
    </div>
  );
}
